name: MfService

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker build -t mfservice-image-name -f ../../MfService/DockerFile
          docker tag mfservice-image-name priteshsaykar/mfservice-image-name:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push priteshsaykar/mfservice-image-name:latest
